update GO_get_associated_ws_objects.yaml to add feature_count and add…
kbase/relation_engine_spec pull request #143
Opened 2020-07-13 16:53 UTC by zhlu9890

… GO_get_associated_ws_features.yaml

2020-07-13 19:47 UTC, jayrbolton requested changes

2020-07-13 19:47 UTC, jayrbolton commented on stored_queries/GO/GO_get_associated_ws_features.yaml
> +  LET flag=IS_NULL(@obj_ref) OR LENGTH(@obj_ref) == 0 ? 1 : 0
Can you rename this to `obj_ref_null` so it's a little clearer what it represents

2020-07-13 19:47 UTC, jayrbolton commented on stored_queries/GO/GO_get_associated_ws_features.yaml
> +  LET flag=IS_NULL(@obj_ref) OR LENGTH(@obj_ref) == 0 ? 1 : 0
Let this variable be a boolean rather than making it an integer in some cases. So:

```
IS_NULL(@obj_ref) OR LENGTH(@obj_ref) == 0
```

2020-07-13 19:47 UTC, jayrbolton commented on stored_queries/GO/GO_get_associated_ws_features.yaml
> +        FILTER v._key == @obj_ref OR 1 == flag
Change to `FILTER v._key == @obj_ref OR obj_ref_null`

2020-07-13 19:47 UTC, jayrbolton commented on stored_queries/GO/GO_get_associated_ws_features.yaml
> +        RETURN DISTINCT {
I don't think the RETURN DISTINCT will work here on nested objects. I would either try to use a COLLECT statement (this is always kind of hard to figure out), or perhaps easier would be to add the following to line 36: 

```OPTIONS {bfs: true, uniqueVertices: "global"}```

2020-07-13 19:47 UTC, jayrbolton commented on stored_queries/GO/GO_get_associated_ws_objects.yaml
> +  FOR r IN raw
Does it work to move this into the above query? 

```
    FOR t in GO_terms
      FILTER t.id == @id
      FILTER t.created <= @ts AND t.expired >= @ts
      LIMIT 1
      FOR v, e, p IN 2 INBOUND t ws_feature_has_GO_annotation, ws_genome_has_feature
        FILTER p.edges[0].created <= @ts AND p.edges[0].expired >= @ts
        FILTER v.is_public OR v.workspace_id IN ws_ids
        SORT v.workspace_id ASC, p.vertices[1].feature_id ASC
        COLLECT ws_obj = v WITH COUNT INTO feature_count
        RETURN DISTINCT {
          ws_obj: KEEP(ws_obj, ['workspace_id', 'object_id', 'version', 'name']),
          feature_count
        }
```

2020-07-14 15:50 UTC, zhlu9890 commented
Hi @jayrbolton, I updated PR as you suggested except the `OPTIONS {bfs: true, uniqueVertices: "global"}` which didn't give results as expected.

2020-07-14 18:26 UTC, merged